#!/bin/bash

# Zaman Bilgisini "Saat:Dakika" şeklinde alıp değişkenlere ataması yapılıyor.
tarih=`date +"%T" | awk -F ":" '{print $1":"$2}'`
saat=`echo $tarih | awk -F ":" '{print $1}'`
dakika=`echo $tarih | awk -F ":" '{print $2}'`

# Saat Denemeleri Yapacağında Aşağıdaki İki Yorum Satırını Kaldır ve Saati gir
#saat="06"
#dakika="05"

# Sistem Saati (Sayıyla) Ekrana Yazdırılıyor.
echo "Sistem Saati : ${saat}:${dakika}"

# Saati Yaklaşık Olarak Hesaplayan Fonksiyon
# Parametreler sırasıyla dakika ve saat
function yaklasikSaat {
	
	if [[ "$1" -ge 00 && "$1" -le 03 ]] ; then
		echo "Saat $2"
	elif [[ "$1" -ge 04 && "$1" -le 07 ]] ; then
		echo "Beş Geçiyor"
	elif [[ "$1" -ge 8 && "$1" -le 12 ]] ; then
		echo "On Geçiyor"
	elif [[ "$1" -ge 13 && "$1" -le 17 ]] ; then
		echo "Çeyrek Geçiyor"
	elif [[ "$1" -ge 18 && "$1" -le 22 ]] ; then
		echo "Yirmi Geçiyor"
	elif [[ "$1" -ge 23 && "$1" -le 27 ]] ; then
		echo "Yirmi Beş Geçiyor"
	elif [[ "$1" -ge 28 && "$1" -le 33 ]] ; then
		echo "Buçuk"
	elif [[ "$1" -ge 34 && "$1" -le 37 ]] ; then
		echo "Yirmi Beş Var"
		yaksaat=$[$2 + 1]
	elif [[ "$1" -ge 38 && "$1" -le 42 ]] ; then
		echo "Yirmi Var"
		yaksaat=$[$2 + 1]
	elif [[ "$1" -ge 43 && "$1" -le 47 ]] ; then
		echo "Çeyrek Var"
		yaksaat=$[$2 + 1]
	elif [[ "$1" -ge 48 && "$1" -le 52 ]] ; then
		echo "On Var"
		yaksaat=$[$2 + 1]
	elif [[ "$1" -ge 53 && "$1" -le 56 ]] ; then
		echo "Beş Var"
		yaksaat=$[$2 + 1]
	elif [[ "$1" -ge 57 && "$1" -le 59 ]] ; then
		echo "Saat Tam"
		yaksaat=$[$2 + 1]
	fi
	
	echo "deneme $yaksaat"
}

# -y parametresi eklenirse saati yaklaşık olarak verir. 
# Bu case programa verilen parametre sayısı üzerinden işlem yapar.
case "$#" in
	1) # Parametre sayısı 1 "bir" ise
		if [ "$1" = "-y" ]
			then
				# parametre "-y" ise
				echo "Yaklaşık Saat"
				yaklasikSaat $dakika $saat
				echo "$saat"
		else
			# parametre "-y" değilse
			echo "Hatalı Parametre"
			exit
		fi
		;;
	0)	# Parametre sayısı 0 "sıfır" ise (Parametre Yoksa)
		echo "Normal Saat"
		;;
	*)
		echo "Fazla Parametre Girdiniz"
		exit
		;;
esac



# Öğlen Akşam İkindi Sabah Gece gibi kavramları hesaplayan bölüm
if [ "${saat:0:1}" = "0" ] ; then
	case "${saat:1:1}" in
		0)
			gun="(Gece yarısı)" ;;
		1|2|3|4)
			gun="(Gece)" ;;
		5|6|7|8|9)
			gun="(Sabah)" ;;
	esac
elif [ "${saat:0:1}" = "1" ] ; then
	case "${saat:1:1}" in
		0|1)
			gun="(Öğleden Önce)"  ;;
		2|3)
			gun="(Öğleyin)"  ;;
		4|5)
			gun="(İkindi)"  ;;
		6|7|8)
			gun="(Akşamüstü)" ;;
		9)
			gun="(Akşam)" ;;
	esac
else
	gun="(Akşam)"
fi

# Saati Yazıya Çeviren Kısım
case "$saat" in
	01|13)
		saat="Biri" ;;
	02|14)
		saat="İkiyi" ;;
	03|15)
		saat="Üçü" ;;
	04|16)
		saat="Dördü" ;;
	05|17)
		saat="Beşi" ;;
	06|18)
		saat="Altıyı" ;;
	07|19)
		saat="Yediyi" ;;
	08|20)
		saat="Sekizi" ;;
	09|21)
		saat="Dokuzu" ;;
	10|22)
		saat="Onu" ;;
	11|23)
		saat="On Biri" ;;
	12|00)
		saat="On İkiyi" ;;
	*)
		echo "Saat Bozuk" ;;
esac

# Dakikanın İlk Hanesini Yazıya Çeviren Kısım
case "${dakika:0:1}" in
	0)
		dakika1="Sıfır" ;;
	1)
		dakika1="On" ;;
	2)
		dakika1="Yirmi" ;;
	3)
		dakika1="Otuz" ;;
	4)
		dakika1="Kırk" ;;
	5)
		dakika1="Elli" ;;
	*)
		dakika1="" ;;
esac

# Dakikanın İkinci Hanesini Yazıya Çeviren Kısım
case "${dakika:1:1}" in
	1)
		dakika2="Bir" ;;
	2)
		dakika2="İki" ;;
	3)
		dakika2="Üç" ;;
	4)
		dakika2="Dört" ;;
	5)
		dakika2="Beş" ;;
	6)
		dakika2="Altı" ;;
	7)
		dakika2="Yedi" ;;
	8)
		dakika2="Sekiz" ;;
	9)
		dakika2="Dokuz" ;;
	*)
		dakika2="" ;;
esac

saat="$gun Saat ${saat} ${dakika1} ${dakika2} geçiyor."

echo "$saat"
