#!/bin/bash

#Zaman Bilgisini "Saat:Dakika" şeklinde alıp değişkenlere ataması yapılıyor.
tarih=`date +"%T" | awk -F ":" '{print $1":"$2}'`
saat=`echo $tarih | awk -F ":" '{print $1}'`
dakika=`echo $tarih | awk -F ":" '{print $2}'`

#Saat Denemeleri Yapacağında Aşağıdaki İki Yorum Satırını Kaldır ve Saati gir
saat="06"
dakika="00"

#Saatin Normal Hali (Sayıyla) Ekrana Yazdırılıyor.
echo "${saat}:${dakika}"

#Öğlen Akşam İkindi Sabah Gece gibi kavramları hesaplayan bölüm
if [ "${saat:0:1}" = "0" ] ; then
	case "${saat:1:1}" in
		0)
			gun="(Gece yarısı)" ;;
		1|2|3|4)
			gun="(Gece)" ;;
		5|6|7|8|9)
			gun="(Sabah)" ;;
	esac
elif [ "${saat:0:1}" = "1" ] ; then
	case "${saat:1:1}" in
		0|1)
			gun="(Öğleden Önce)"  ;;
		2|3)
			gun="(Öğleyin)"  ;;
		4|5)
			gun="(İkindi)"  ;;
		6|7|8)
			gun="(Akşamüstü)" ;;
		9)
			gun="(Akşam)" ;;
	esac
else
	gun="(Akşam)"
fi


case "$saat" in
	01|13)
		saat="Biri" ;;
	02|14)
		saat="İkiyi" ;;
	03|15)
		saat="Üçü" ;;
	04|16)
		saat="Dördü" ;;
	05|17)
		saat="Beşi" ;;
	06|18)
		saat="Altıyı" ;;
	07|19)
		saat="Yediyi" ;;
	08|20)
		saat="Sekizi" ;;
	09|21)
		saat="Dokuzu" ;;
	10|22)
		saat="Onu" ;;
	11|23)
		saat="On Biri" ;;
	12|00)
		saat="On İkiyi" ;;
	*)
		echo "Saat Bozuk" ;;
esac

case "${dakika:0:1}" in
	1)
		dakika1="On" ;;
	2)
		dakika1="Yirmi" ;;
	3)
		dakika1="Otuz" ;;
	4)
		dakika1="Kırk" ;;
	5)
		dakika1="Elli" ;;
	*)
		dakika1="" ;;
esac

case "${dakika:1:1}" in
	1)
		dakika2="Bir" ;;
	2)
		dakika2="İki" ;;
	3)
		dakika2="Üç" ;;
	4)
		dakika2="Dört" ;;
	5)
		dakika2="Beş" ;;
	6)
		dakika2="Altı" ;;
	7)
		dakika2="Yedi" ;;
	8)
		dakika2="Sekiz" ;;
	9)
		dakika2="Dokuz" ;;
	0)
		dakika2="Sıfır" ;;
	*)
		dakika2="" ;;
esac

saat="$gun Saat ${saat} ${dakika1} ${dakika2} geçiyor."

echo "$saat"
